### ISSUE TITLE
add hand 4122?

### ISSUE THREAD

**Issue by lianghongzhuo** [shadow-robot/sr_hand_config#58]
I have updated our hand 4122 at https://github.com/TAMS-Group/sr_hand_config/commit/c643b41b8004096009a3df957d5be3fd10251bc3

Is it make sense to also put it here?

**Comment by v4hn** [comment]
@biofotis @SergioShadow @Juanjojld

What is Shadow's policy on adding existing hands here?
Isn't this needed for a full "noetic" stack with your current upstream branches?
Should we keep custom forks around ourselves? @lianghongzhuo [forked it for us for now](https://github.com/TAMS-Group/sr_hand_config).

**Comment by biofotis** [comment]
Sorry I didnt receive any notification before. Yes if you could make a PR here we will merge it. Its worth having it here as is already included in our docker images.
